name = "SuckerSim"
uuid = "533a791a-0366-454d-b9e4-91fcf580b0fc"
authors = ["sandsq"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
