name = "SuckerSim"
uuid = "533a791a-0366-454d-b9e4-91fcf580b0fc"
authors = ["sandsq"]
version = "1.0.0-DEV"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Logging = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
